### PR TITLE
467 notfound old docs

### LINKED ISSUE #467: 404 page: add catch for old-doc links received
@dcroote suggested:

> For the broken links to older Airnode versions, is there a way to perhaps have the 404 page link to the old docs if the url contains v0.5, v0.6, v0.7, etc.? For example, I get a 404 here: https://docs.api3.org/airnode/v0.9/reference/migration.html but that URL would work if I just had "old-" prefixed in the domain name, so the 404 could provide that suggestion along with text like "It looks like you are looking for the documentation for an older Airnode version, try: <referring URL but with prefix> or browse the latest docs here"

### PR DESCRIPTION
**Pull request by wkande**
Closes #467 

When a reader uses an older link from `api3-doc` that included an Airnode or OIS version they of course get a 404. Now the 404 page looks for this and offers them a simple explanation and a button to get where they want to be.

### CODE REVIEW

**Comment by wkande** [comment]
Screenshot 2023-05-10 at 12 06 20 PM

File: docs/_components/vitepress/NotFound.vue [hunk 1]
```diff
@@ -58,12 +67,29 @@ onMounted(() => {
...
   <div class="NotFound" v-if="showMsg === 1">
     <p class="code">404</p>
     <h1 class="title">PAGE NOT FOUND</h1>
     <div class="divider" />
-    <blockquote class="quote">
+
+    <!-- GO TO LEGACY DOCS -->
+    <blockquote class="quote" v-if="legacyURL">
+      <hr />
+      The URL send appears to be a page from the legacy documentation. The
```
Comment (dcroote) [inline docs/_components/vitepress/NotFound.vue:79]: I'm not sure what "send" means here. Perhaps "The URL you are requesting appears to a page belonging to the legacy documentation."

**Review by dcroote — COMMENTED** [review]
I tried several Airnode and OIS links and it works nicely, I have only one comment on the language.

**Review by dcroote — APPROVED** [review]
Whoops meant to approve in my review above

File: docs/_components/vitepress/NotFound.vue (hunk 1 above)
Comment (wkande) [reply docs/_components/vitepress/NotFound.vue:79]: Typo **send** > **sent**. But now I like:

"The page you are requesting appears to 
be in the legacy documentation. The
      button below should take you there."
